<Project Sdk="Meadow.Sdk/1.1.0">
 <PropertyGroup>
   <TargetFramework>net10.0</TargetFramework>
   <OutputType>Library</OutputType>
   <AssemblyName>Meadow.Contracts</AssemblyName>   
    <Company>Wilderness Labs, Inc</Company>
   <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/</PackageProjectUrl>
   <PackageId>Meadow.Contracts</PackageId>
   <PackageIcon>icon.png</PackageIcon>
   <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Contracts</RepositoryUrl>
   <PackageTags>Meadow</PackageTags>
   <Description>Wilderness Labs contracts for .NET applications on Meadow hardware</Description>
   <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
   <RootNamespace>Meadow</RootNamespace>
    <Nullable>enable</Nullable>
   <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
   <NoWarn>CS8597;CS8600;CS8601;CS8602;CS8603;CS8604;CS8605;CS8612;CS8618;CS8619;CS8622;CS8714;CS8765;CS8767</NoWarn>
 </PropertyGroup>
 <PropertyGroup>
    <Authors>Wilderness Labs, Inc</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <LangVersion>12.0</LangVersion>
 </PropertyGroup>
    <ItemGroup>
        <None Include="icon.png" Link="icon.png" Pack="true" PackagePath="" />
    </ItemGroup>
    <ItemGroup>
    <ProjectReference Include="..\..\..\Meadow.Logging\Source\Meadow.Logging\lib\Meadow.Logging.csproj" />
    <ProjectReference Include="..\..\..\Meadow.Units\Source\Meadow.Units\Meadow.Units.csproj" />
    </ItemGroup>
</Project>
