name: Develop Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout Meadow.Logging
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop
        
    - name: Checkout Meadow.Units
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v4
      with:
        path: Meadow.Contracts
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version:
          8.0.x
    
    - name: Build Meadow.Contracts
      run: dotnet build -c Release Meadow.Contracts/Source/Meadow.Contracts/Meadow.Contracts.sln